[workspace]
resolver = "2"
members = ["rmk/core", "rmk/chips/*"]

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true

[profile.release]
debug = false
lto = true
opt-level = "z"
incremental = true
