# this is used to emulate the firmware on a computer
# [features.chip_type_emulator]
# do NOT use this as a real chip

[keyboard]
product_id = 0x0000
vendor_id = 0x0000
name = "Devboard"
manufacturer = "Devboard"
chip = "stm32f411ceu"
storage = 256

[settings]
keycodes = "german"
debounce_time = 10
tapping_term = 220

[behaviors]
hold = true
tap = true

[actions]
mouse = true

[flavors]
space_cadet = true

[matrix]
row_count = 1
col_count = 0
# https://github.com/ostrosco/device_query/blob/master/src/keymap.rs
row_pins = ["PB9"]
col_pins = []
layout = [[0,0]]

[rgb]
data_pin = "PA7"

[swd]
swo = "PB2"
swclk = "PA14"
swdio = "PA15"
