# this is used to emulate the firmware on a computer
# [features.chip_type_emulator]
# do NOT use this as a real chip

[keyboard]
product_id = 0x0000
vendor_id = 0x0000
name = "Devboard"
manufacturer = "Devboard"
chip = "stm32f411ceu-16mhz-internal"
storage = 256

[settings]
keycodes = "german"
debounce_time = 10
tapping_term = 220
analogue_read = true

[behaviors]
hold = true
tap = true

[actions]
mouse = true

[flavors]
space_cadet = true

[multiplexers]
count = 3
channels = 16
com_pins = ["PA0", "PA1", "PA2"]
sel_pins = ["PB4", "PB5", "PB7", "PB6"]  
layout = [
  [0,9],  [0,11], [0,13],  [0,14], [1,10], [1,11], [1,12], [1,15], [2,10], [2,11], [2,12], [2,14],
  [0,8],  [0,12], [0,15],  [1,9],  [1,8],  [1,13], [1,14], [2,9],  [2,8],  [2,13],         [2,15],
  [0,6],  [0,7],  [0,0],   [1,5],  [1,4],  [1,3],  [1,0],  [2,6],  [2,5],          [2,3],  [2,0],
  [0,3],  [0,2],  [0,1],           [1,2],          [1,1],                  [2,4],  [2,2],  [2,1],
]

[rgb]
data_pin = "PA7"

[swd]
swo = "PB2"
swclk = "PA14"
swdio = "PA15"
