# this defines the default settings for a keyboard

[keyboard]
product_id = 0x0000
vendor_id = 0x0000
name = ""
manufacturer = ""
chip = ""
key_count = 0
keycodes = "us"

[settings]
debounce_time = 10 // ms
tapping_term = 220 // ms
analogue_read = false

[behaviors]
press = true
hold = true

[matrix]
row_count = 0
col_count = 0
row_pins = []
col_pins = []

# [multiplexers]
# count = 0
# channels = 0
# sel_pins = []
# com_pins = []

[layout]
keys = []

[rgb]
data_pin = ""

[swd]
swo = ""
swclk = ""
swdio = ""
