# this is used to emulate the firmware on a computer
# [features.family_EMULATOR]
# do NOT use this as a real chip


[keyboard]
product_id = 0x0000
vendor_id = 0x0000
name = "Emulator"
manufacturer = "Emulator"
chip = "_emulator"
# keycodes = "german" # changes keycodes to represent a french keyboard


[settings]
debounce_time = 10
tapping_term = 220

[behaviors]
hold = true
tap = true

[actions]
mouse = true

[flavors]
space_cadet = true

[matrix]
row_count = 1
col_count = 0
# https://github.com/ostrosco/device_query/blob/master/src/keymap.rs
row_pins = ["Q", "W", "E", "R"]
col_pins = []
layout = [
  [0,0], [1,0], [2,0], [3,0]
]

[rgb]
data_pin = "PA7"

[swd]
swo = "PB2"
swclk = "PA14"
swdio = "PA15"
