[keyboard]
product_id = 0x0000
vendor_id = 0x0000
name = "Feb42"
manufacturer = "febreeze"
chip = "stm32f303cbtx"

[settings]
# keycodes = "german" # changes keycodes to represent a french keyboard
debounce_time = 10
tapping_term = 220
analogue_read = true # default false

[behaviors]
press = true
hold = true

[multiplexers]
count = 3
channels = 16
sel_pins = ["PB3", "PB4", "PB6", "PB5"]
com_pins = ["PA13", "PA10", "PA9"]
layout = [
  [0,9], [0,1], [0,3], [0,4], [1,0], [1,1], [1,2], [1,5], [2,0], [2,1], [2,2], [2,4],
  [0,8], [0,2], [0,5], [1,9], [1,8], [1,3], [1,4], [2,9], [2,8], [2,3], [0,6],
  [0,7], [0,0], [1,5], [1,4], [1,3], [1,0], [2,6], [2,5], [2,3], [2,0], [0,3],
  [0,2], [0,1], [0,1], [1,2], [1,1], [2,4], [2,2], [2,1],
]

[rgb]
data_pin = "PA7"

[swd]
swo = "PB2"
swclk = "PA14"
swdio = "PA15"
