[target.thumbv7em-none-eabi]
runner = 'probe-rs run --chip STM32F411CEUx'

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
