[package]
name = "orbit-macros"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
resolver = "2"

[dependencies]
toml = "0.8"
quote = "1.0"
proc-macro2 = "1.0"

[features]
chip_type_none = []
chip_type_emulator = []
chip_type_stm32 = []
chip_type_nrf = []
chip_type_esp = []
chip_type_rp = []
chip_type_chw = []
default = []

[lib]
proc-macro = true