# this is the user configuration file
# each setting will be merged into the parent keyboard configuration
# you can override any setting here
# 
# in case you dont want to use a preset keyboard
# you can use make kb=_none_ to only use the configuration in this file

# [keyboard]
# keycodes = "german"

[behaviors]
press = true
hold = true
modding = true
