name: Build RMK Firmware

on:
  workflow_call:
    inputs:
      keyboard:
        description: "which keyboard to use"
        default: ""
        required: true
        type: string

jobs:
  build:
    name: Firmware
    runs-on: ubuntu-latest
    container: rmkfirmware/rmk:latest
    
    steps:
      - name: Checkout rmk
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          repository: rmk-firmware/rmk
          ref: master

      - name: Checkout User Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          fetch-depth: 0

      - name: Compile Firmware
        run: |
          make build kb=${{ inputs.keyboard }}
      
      - name: Generate Release
        uses: softprops/action-gh-release@v2
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: Latest Firmware
          tag_name: ${{ inputs.release_name || 'latest' }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            *.hex
            *.bin

      